#!/usr/bin/env python3
"""
Build a local embedding index from resolved ticket training pairs.

Input
-----
`extracted_pairs.jsonl` generated by tdx_ollama_pair_builder.py

Output
------
An index directory containing:
- records.jsonl       metadata and original text for each indexed record
- embeddings.npy      normalized embedding matrix
- index_metadata.json build settings and model metadata

Example
-------
python build_ticket_index.py ^
  --input out_pairs_test_20/extracted_pairs.jsonl ^
  --model models/ticket-pairs ^
  --output-dir retrieval_index
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import numpy as np
from sentence_transformers import SentenceTransformer


DEFAULT_TEXT_MODE = "query_positive"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a local embedding index from resolved ticket pairs.")
    parser.add_argument("--input", required=True, help="Path to extracted_pairs.jsonl")
    parser.add_argument("--model", required=True, help="SentenceTransformer model path or model name")
    parser.add_argument("--output-dir", required=True, help="Directory for the saved index")
    parser.add_argument(
        "--text-mode",
        choices=["query", "query_positive"],
        default=DEFAULT_TEXT_MODE,
        help="Text to embed for retrieval",
    )
    parser.add_argument("--batch-size", type=int, default=64, help="Embedding batch size")
    return parser.parse_args()


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def load_pairs(path: Path) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            raw = line.strip()
            if not raw:
                continue
            try:
                obj = json.loads(raw)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSONL at line {line_no}: {exc}") from exc
            if not isinstance(obj, dict):
                raise ValueError(f"Expected object at line {line_no}")
            rows.append(obj)
    return rows


def build_index_text(row: Dict[str, object], text_mode: str) -> str:
    query = str(row.get("query") or "").strip()
    positive = str(row.get("positive") or "").strip()
    if text_mode == "query_positive" and positive:
        return f"Issue: {query}\nResolution: {positive}".strip()
    return query


def write_jsonl(path: Path, rows: List[Dict[str, object]]) -> None:
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    output_dir = Path(args.output_dir)

    if not input_path.exists():
        print(f"Input file not found: {input_path}", file=sys.stderr)
        return 1

    rows = load_pairs(input_path)
    if not rows:
        print("No extracted pairs found.", file=sys.stderr)
        return 1

    model = SentenceTransformer(args.model)

    records: List[Dict[str, object]] = []
    texts: List[str] = []
    for row in rows:
        index_text = build_index_text(row, args.text_mode)
        if not index_text:
            continue
        records.append(
            {
                "ticket_id": row.get("ticket_id"),
                "query": row.get("query"),
                "positive": row.get("positive"),
                "issue_category": row.get("issue_category"),
                "confidence": row.get("confidence"),
                "title": row.get("title"),
                "status": row.get("status"),
                "index_text": index_text,
            }
        )
        texts.append(index_text)

    if not texts:
        print("No usable texts were found for indexing.", file=sys.stderr)
        return 1

    embeddings = model.encode(
        texts,
        batch_size=args.batch_size,
        convert_to_numpy=True,
        normalize_embeddings=True,
        show_progress_bar=True,
    )

    ensure_dir(output_dir)
    records_path = output_dir / "records.jsonl"
    embeddings_path = output_dir / "embeddings.npy"
    metadata_path = output_dir / "index_metadata.json"

    write_jsonl(records_path, records)
    np.save(embeddings_path, embeddings)
    metadata_path.write_text(
        json.dumps(
            {
                "input": str(input_path),
                "model": args.model,
                "text_mode": args.text_mode,
                "count": len(records),
                "embedding_dim": int(embeddings.shape[1]),
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    print(f"Indexed records: {len(records)}")
    print(f"Wrote: {records_path}")
    print(f"Wrote: {embeddings_path}")
    print(f"Wrote: {metadata_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
